server:
  port: 8025
  
spring:
  application: 
    name: CLOUD-GATEWAY

zuul:
  prefix: /api
  routes:
    study:
      path: /study/**
      serviceId: COLLEGE-SERVICE
    people:
      path: /people/**
      serviceId: STUDENT-SERVICE

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread: timeoutInMilliseconds:4000
          
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
      
Eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost      
            